/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardDTO
 */
export interface CardDTO {
    /**
     * 
     * @type {number}
     * @memberof CardDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CardDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CardDTO
     */
    type?: string;
}

/**
 * Check if a given object implements the CardDTO interface.
 */
export function instanceOfCardDTO(value: object): value is CardDTO {
    return true;
}

export function CardDTOFromJSON(json: any): CardDTO {
    return CardDTOFromJSONTyped(json, false);
}

export function CardDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function CardDTOToJSON(json: any): CardDTO {
    return CardDTOToJSONTyped(json, false);
}

export function CardDTOToJSONTyped(value?: CardDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
    };
}

