/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CardDTO } from './CardDTO';
import {
    CardDTOFromJSON,
    CardDTOFromJSONTyped,
    CardDTOToJSON,
    CardDTOToJSONTyped,
} from './CardDTO';

/**
 * 
 * @export
 * @interface DeckDTO
 */
export interface DeckDTO {
    /**
     * 
     * @type {string}
     * @memberof DeckDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DeckDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DeckDTO
     */
    description?: string;
    /**
     * 
     * @type {Array<CardDTO>}
     * @memberof DeckDTO
     */
    mainDeck?: Array<CardDTO>;
    /**
     * 
     * @type {Array<CardDTO>}
     * @memberof DeckDTO
     */
    sideDeck?: Array<CardDTO>;
    /**
     * 
     * @type {Array<CardDTO>}
     * @memberof DeckDTO
     */
    extraDeck?: Array<CardDTO>;
}

/**
 * Check if a given object implements the DeckDTO interface.
 */
export function instanceOfDeckDTO(value: object): value is DeckDTO {
    return true;
}

export function DeckDTOFromJSON(json: any): DeckDTO {
    return DeckDTOFromJSONTyped(json, false);
}

export function DeckDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeckDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'mainDeck': json['mainDeck'] == null ? undefined : ((json['mainDeck'] as Array<any>).map(CardDTOFromJSON)),
        'sideDeck': json['sideDeck'] == null ? undefined : ((json['sideDeck'] as Array<any>).map(CardDTOFromJSON)),
        'extraDeck': json['extraDeck'] == null ? undefined : ((json['extraDeck'] as Array<any>).map(CardDTOFromJSON)),
    };
}

export function DeckDTOToJSON(json: any): DeckDTO {
    return DeckDTOToJSONTyped(json, false);
}

export function DeckDTOToJSONTyped(value?: DeckDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'mainDeck': value['mainDeck'] == null ? undefined : ((value['mainDeck'] as Array<any>).map(CardDTOToJSON)),
        'sideDeck': value['sideDeck'] == null ? undefined : ((value['sideDeck'] as Array<any>).map(CardDTOToJSON)),
        'extraDeck': value['extraDeck'] == null ? undefined : ((value['extraDeck'] as Array<any>).map(CardDTOToJSON)),
    };
}

