/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PDFCreationRequest
 */
export interface PDFCreationRequest {
    /**
     * 
     * @type {number}
     * @memberof PDFCreationRequest
     */
    marginLeft?: number;
    /**
     * 
     * @type {number}
     * @memberof PDFCreationRequest
     */
    marginTop?: number;
    /**
     * 
     * @type {number}
     * @memberof PDFCreationRequest
     */
    horizontalSpacing?: number;
    /**
     * 
     * @type {number}
     * @memberof PDFCreationRequest
     */
    verticalSpacing?: number;
    /**
     * 
     * @type {number}
     * @memberof PDFCreationRequest
     */
    cardWidthMM?: number;
    /**
     * 
     * @type {number}
     * @memberof PDFCreationRequest
     */
    cardHeightMM?: number;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof PDFCreationRequest
     */
    images?: Array<Blob>;
}

/**
 * Check if a given object implements the PDFCreationRequest interface.
 */
export function instanceOfPDFCreationRequest(value: object): value is PDFCreationRequest {
    return true;
}

export function PDFCreationRequestFromJSON(json: any): PDFCreationRequest {
    return PDFCreationRequestFromJSONTyped(json, false);
}

export function PDFCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PDFCreationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'marginLeft': json['marginLeft'] == null ? undefined : json['marginLeft'],
        'marginTop': json['marginTop'] == null ? undefined : json['marginTop'],
        'horizontalSpacing': json['horizontalSpacing'] == null ? undefined : json['horizontalSpacing'],
        'verticalSpacing': json['verticalSpacing'] == null ? undefined : json['verticalSpacing'],
        'cardWidthMM': json['cardWidthMM'] == null ? undefined : json['cardWidthMM'],
        'cardHeightMM': json['cardHeightMM'] == null ? undefined : json['cardHeightMM'],
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function PDFCreationRequestToJSON(json: any): PDFCreationRequest {
    return PDFCreationRequestToJSONTyped(json, false);
}

export function PDFCreationRequestToJSONTyped(value?: PDFCreationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'marginLeft': value['marginLeft'],
        'marginTop': value['marginTop'],
        'horizontalSpacing': value['horizontalSpacing'],
        'verticalSpacing': value['verticalSpacing'],
        'cardWidthMM': value['cardWidthMM'],
        'cardHeightMM': value['cardHeightMM'],
        'images': value['images'],
    };
}

