/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YugiohDataPrice
 */
export interface YugiohDataPrice {
    /**
     * 
     * @type {number}
     * @memberof YugiohDataPrice
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataPrice
     */
    cardmarketPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataPrice
     */
    tcgplayerPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataPrice
     */
    ebayPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataPrice
     */
    amazonPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataPrice
     */
    coolstuffincPrice?: string;
}

/**
 * Check if a given object implements the YugiohDataPrice interface.
 */
export function instanceOfYugiohDataPrice(value: object): value is YugiohDataPrice {
    return true;
}

export function YugiohDataPriceFromJSON(json: any): YugiohDataPrice {
    return YugiohDataPriceFromJSONTyped(json, false);
}

export function YugiohDataPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): YugiohDataPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'cardmarketPrice': json['cardmarket_price'] == null ? undefined : json['cardmarket_price'],
        'tcgplayerPrice': json['tcgplayer_price'] == null ? undefined : json['tcgplayer_price'],
        'ebayPrice': json['ebay_price'] == null ? undefined : json['ebay_price'],
        'amazonPrice': json['amazon_price'] == null ? undefined : json['amazon_price'],
        'coolstuffincPrice': json['coolstuffinc_price'] == null ? undefined : json['coolstuffinc_price'],
    };
}

export function YugiohDataPriceToJSON(json: any): YugiohDataPrice {
    return YugiohDataPriceToJSONTyped(json, false);
}

export function YugiohDataPriceToJSONTyped(value?: YugiohDataPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cardmarket_price': value['cardmarketPrice'],
        'tcgplayer_price': value['tcgplayerPrice'],
        'ebay_price': value['ebayPrice'],
        'amazon_price': value['amazonPrice'],
        'coolstuffinc_price': value['coolstuffincPrice'],
    };
}

