/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YugiohDataImage
 */
export interface YugiohDataImage {
    /**
     * 
     * @type {number}
     * @memberof YugiohDataImage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataImage
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataImage
     */
    imageUrlSmall?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataImage
     */
    imageUrlCropped?: string;
}

/**
 * Check if a given object implements the YugiohDataImage interface.
 */
export function instanceOfYugiohDataImage(value: object): value is YugiohDataImage {
    return true;
}

export function YugiohDataImageFromJSON(json: any): YugiohDataImage {
    return YugiohDataImageFromJSONTyped(json, false);
}

export function YugiohDataImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): YugiohDataImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'imageUrlSmall': json['image_url_small'] == null ? undefined : json['image_url_small'],
        'imageUrlCropped': json['image_url_cropped'] == null ? undefined : json['image_url_cropped'],
    };
}

export function YugiohDataImageToJSON(json: any): YugiohDataImage {
    return YugiohDataImageToJSONTyped(json, false);
}

export function YugiohDataImageToJSONTyped(value?: YugiohDataImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'image_url': value['imageUrl'],
        'image_url_small': value['imageUrlSmall'],
        'image_url_cropped': value['imageUrlCropped'],
    };
}

