/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { YugiohDataImage } from './YugiohDataImage';
import {
    YugiohDataImageFromJSON,
    YugiohDataImageFromJSONTyped,
    YugiohDataImageToJSON,
    YugiohDataImageToJSONTyped,
} from './YugiohDataImage';
import type { YugiohDataSet } from './YugiohDataSet';
import {
    YugiohDataSetFromJSON,
    YugiohDataSetFromJSONTyped,
    YugiohDataSetToJSON,
    YugiohDataSetToJSONTyped,
} from './YugiohDataSet';
import type { YugiohDataPrice } from './YugiohDataPrice';
import {
    YugiohDataPriceFromJSON,
    YugiohDataPriceFromJSONTyped,
    YugiohDataPriceToJSON,
    YugiohDataPriceToJSONTyped,
} from './YugiohDataPrice';

/**
 * 
 * @export
 * @interface YugiohDataCard
 */
export interface YugiohDataCard {
    /**
     * 
     * @type {number}
     * @memberof YugiohDataCard
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    humanReadableCardType?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    frameType?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    desc?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    race?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    nameEn?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataCard
     */
    ygoprodeckUrl?: string;
    /**
     * 
     * @type {Array<YugiohDataSet>}
     * @memberof YugiohDataCard
     */
    cardSets?: Array<YugiohDataSet>;
    /**
     * 
     * @type {Array<YugiohDataImage>}
     * @memberof YugiohDataCard
     */
    cardImages?: Array<YugiohDataImage>;
    /**
     * 
     * @type {Array<YugiohDataPrice>}
     * @memberof YugiohDataCard
     */
    cardPrices?: Array<YugiohDataPrice>;
}

/**
 * Check if a given object implements the YugiohDataCard interface.
 */
export function instanceOfYugiohDataCard(value: object): value is YugiohDataCard {
    return true;
}

export function YugiohDataCardFromJSON(json: any): YugiohDataCard {
    return YugiohDataCardFromJSONTyped(json, false);
}

export function YugiohDataCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): YugiohDataCard {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'humanReadableCardType': json['humanReadableCardType'] == null ? undefined : json['humanReadableCardType'],
        'frameType': json['frameType'] == null ? undefined : json['frameType'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'race': json['race'] == null ? undefined : json['race'],
        'nameEn': json['name_en'] == null ? undefined : json['name_en'],
        'ygoprodeckUrl': json['ygoprodeck_url'] == null ? undefined : json['ygoprodeck_url'],
        'cardSets': json['card_sets'] == null ? undefined : ((json['card_sets'] as Array<any>).map(YugiohDataSetFromJSON)),
        'cardImages': json['card_images'] == null ? undefined : ((json['card_images'] as Array<any>).map(YugiohDataImageFromJSON)),
        'cardPrices': json['card_prices'] == null ? undefined : ((json['card_prices'] as Array<any>).map(YugiohDataPriceFromJSON)),
    };
}

export function YugiohDataCardToJSON(json: any): YugiohDataCard {
    return YugiohDataCardToJSONTyped(json, false);
}

export function YugiohDataCardToJSONTyped(value?: YugiohDataCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'humanReadableCardType': value['humanReadableCardType'],
        'frameType': value['frameType'],
        'desc': value['desc'],
        'race': value['race'],
        'name_en': value['nameEn'],
        'ygoprodeck_url': value['ygoprodeckUrl'],
        'card_sets': value['cardSets'] == null ? undefined : ((value['cardSets'] as Array<any>).map(YugiohDataSetToJSON)),
        'card_images': value['cardImages'] == null ? undefined : ((value['cardImages'] as Array<any>).map(YugiohDataImageToJSON)),
        'card_prices': value['cardPrices'] == null ? undefined : ((value['cardPrices'] as Array<any>).map(YugiohDataPriceToJSON)),
    };
}

