/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { YugiohDataCard } from './YugiohDataCard';
import {
    YugiohDataCardFromJSON,
    YugiohDataCardFromJSONTyped,
    YugiohDataCardToJSON,
    YugiohDataCardToJSONTyped,
} from './YugiohDataCard';

/**
 * 
 * @export
 * @interface YugiohDeck
 */
export interface YugiohDeck {
    /**
     * 
     * @type {string}
     * @memberof YugiohDeck
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDeck
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDeck
     */
    description?: string;
    /**
     * 
     * @type {Array<YugiohDataCard>}
     * @memberof YugiohDeck
     */
    mainDeck?: Array<YugiohDataCard>;
    /**
     * 
     * @type {Array<YugiohDataCard>}
     * @memberof YugiohDeck
     */
    sideDeck?: Array<YugiohDataCard>;
    /**
     * 
     * @type {Array<YugiohDataCard>}
     * @memberof YugiohDeck
     */
    extraDeck?: Array<YugiohDataCard>;
}

/**
 * Check if a given object implements the YugiohDeck interface.
 */
export function instanceOfYugiohDeck(value: object): value is YugiohDeck {
    return true;
}

export function YugiohDeckFromJSON(json: any): YugiohDeck {
    return YugiohDeckFromJSONTyped(json, false);
}

export function YugiohDeckFromJSONTyped(json: any, ignoreDiscriminator: boolean): YugiohDeck {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'mainDeck': json['mainDeck'] == null ? undefined : ((json['mainDeck'] as Array<any>).map(YugiohDataCardFromJSON)),
        'sideDeck': json['sideDeck'] == null ? undefined : ((json['sideDeck'] as Array<any>).map(YugiohDataCardFromJSON)),
        'extraDeck': json['extraDeck'] == null ? undefined : ((json['extraDeck'] as Array<any>).map(YugiohDataCardFromJSON)),
    };
}

export function YugiohDeckToJSON(json: any): YugiohDeck {
    return YugiohDeckToJSONTyped(json, false);
}

export function YugiohDeckToJSONTyped(value?: YugiohDeck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'mainDeck': value['mainDeck'] == null ? undefined : ((value['mainDeck'] as Array<any>).map(YugiohDataCardToJSON)),
        'sideDeck': value['sideDeck'] == null ? undefined : ((value['sideDeck'] as Array<any>).map(YugiohDataCardToJSON)),
        'extraDeck': value['extraDeck'] == null ? undefined : ((value['extraDeck'] as Array<any>).map(YugiohDataCardToJSON)),
    };
}

