/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YugiohDataSet
 */
export interface YugiohDataSet {
    /**
     * 
     * @type {number}
     * @memberof YugiohDataSet
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataSet
     */
    setName?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataSet
     */
    setCode?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataSet
     */
    setRarity?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataSet
     */
    setRarityCode?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDataSet
     */
    setPrice?: string;
}

/**
 * Check if a given object implements the YugiohDataSet interface.
 */
export function instanceOfYugiohDataSet(value: object): value is YugiohDataSet {
    return true;
}

export function YugiohDataSetFromJSON(json: any): YugiohDataSet {
    return YugiohDataSetFromJSONTyped(json, false);
}

export function YugiohDataSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): YugiohDataSet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'setName': json['set_name'] == null ? undefined : json['set_name'],
        'setCode': json['set_code'] == null ? undefined : json['set_code'],
        'setRarity': json['set_rarity'] == null ? undefined : json['set_rarity'],
        'setRarityCode': json['set_rarity_code'] == null ? undefined : json['set_rarity_code'],
        'setPrice': json['set_price'] == null ? undefined : json['set_price'],
    };
}

export function YugiohDataSetToJSON(json: any): YugiohDataSet {
    return YugiohDataSetToJSONTyped(json, false);
}

export function YugiohDataSetToJSONTyped(value?: YugiohDataSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'set_name': value['setName'],
        'set_code': value['setCode'],
        'set_rarity': value['setRarity'],
        'set_rarity_code': value['setRarityCode'],
        'set_price': value['setPrice'],
    };
}

