/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeckDTO } from './DeckDTO';
import {
    DeckDTOFromJSON,
    DeckDTOFromJSONTyped,
    DeckDTOToJSON,
    DeckDTOToJSONTyped,
} from './DeckDTO';

/**
 * 
 * @export
 * @interface YugiohDeckCreationResponse
 */
export interface YugiohDeckCreationResponse {
    /**
     * 
     * @type {DeckDTO}
     * @memberof YugiohDeckCreationResponse
     */
    deck?: DeckDTO;
    /**
     * 
     * @type {Array<string>}
     * @memberof YugiohDeckCreationResponse
     */
    unparsable?: Array<string>;
}

/**
 * Check if a given object implements the YugiohDeckCreationResponse interface.
 */
export function instanceOfYugiohDeckCreationResponse(value: object): value is YugiohDeckCreationResponse {
    return true;
}

export function YugiohDeckCreationResponseFromJSON(json: any): YugiohDeckCreationResponse {
    return YugiohDeckCreationResponseFromJSONTyped(json, false);
}

export function YugiohDeckCreationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): YugiohDeckCreationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deck': json['deck'] == null ? undefined : DeckDTOFromJSON(json['deck']),
        'unparsable': json['unparsable'] == null ? undefined : json['unparsable'],
    };
}

export function YugiohDeckCreationResponseToJSON(json: any): YugiohDeckCreationResponse {
    return YugiohDeckCreationResponseToJSONTyped(json, false);
}

export function YugiohDeckCreationResponseToJSONTyped(value?: YugiohDeckCreationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deck': DeckDTOToJSON(value['deck']),
        'unparsable': value['unparsable'],
    };
}

