/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YugiohDeckCreationRequest
 */
export interface YugiohDeckCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof YugiohDeckCreationRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof YugiohDeckCreationRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof YugiohDeckCreationRequest
     */
    cards?: Array<string>;
}

/**
 * Check if a given object implements the YugiohDeckCreationRequest interface.
 */
export function instanceOfYugiohDeckCreationRequest(value: object): value is YugiohDeckCreationRequest {
    return true;
}

export function YugiohDeckCreationRequestFromJSON(json: any): YugiohDeckCreationRequest {
    return YugiohDeckCreationRequestFromJSONTyped(json, false);
}

export function YugiohDeckCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): YugiohDeckCreationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'cards': json['cards'] == null ? undefined : json['cards'],
    };
}

export function YugiohDeckCreationRequestToJSON(json: any): YugiohDeckCreationRequest {
    return YugiohDeckCreationRequestToJSONTyped(json, false);
}

export function YugiohDeckCreationRequestToJSONTyped(value?: YugiohDeckCreationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'cards': value['cards'],
    };
}

