# Azure Connection String
application.storage.connectionString=
# Azure Container Name
application.storage.containerName=akamai
# Path where to find the stored logs. In this case the logs are in /logs/2025/08/22
application.storage.sourcePath=logs/2026/06
# Path where to store the merged logs
application.storage.targetPath=merged-logs
# Delete merged logs after processing
application.mode.delete=true

# Clickhouse
clickhouse.url=http://localhost:8123
clickhouse.username=default
clickhouse.password=

application.ingestion.clickhouse=true
application.ingestion.merge=true
