# SharePoint configuration

sharepoint.baseUrl=https://graph.microsoft.com/v1.0
sharepoint.clientId=
sharepoint.clientSecret=
sharepoint.tenantId=

# SharePoint request configuration
sharepoint.filter=
sharepoint.fields=fields
sharepoint.sort=
# SiteId looks like this: "test.sharepoint.com:/sites/TestSite:" #veryWeird
sharepoint.siteId=
sharepoint.listId=
