/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeckDTO,
  YugiohDeckCreationRequest,
  YugiohDeckCreationResponse,
} from '../models/index';
import {
    DeckDTOFromJSON,
    DeckDTOToJSON,
    YugiohDeckCreationRequestFromJSON,
    YugiohDeckCreationRequestToJSON,
    YugiohDeckCreationResponseFromJSON,
    YugiohDeckCreationResponseToJSON,
} from '../models/index';

export interface CreateDeckRequest {
    yugiohDeckCreationRequest: YugiohDeckCreationRequest;
}

export interface DeleteIdRequest {
    id: string;
}

export interface GetDeckByIdRequest {
    id: string;
}

/**
 * 
 */
export class YugiohDeckControllerApi extends runtime.BaseAPI {

    /**
     */
    async createDeckRaw(requestParameters: CreateDeckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<YugiohDeckCreationResponse>> {
        if (requestParameters['yugiohDeckCreationRequest'] == null) {
            throw new runtime.RequiredError(
                'yugiohDeckCreationRequest',
                'Required parameter "yugiohDeckCreationRequest" was null or undefined when calling createDeck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/deck/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: YugiohDeckCreationRequestToJSON(requestParameters['yugiohDeckCreationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => YugiohDeckCreationResponseFromJSON(jsonValue));
    }

    /**
     */
    async createDeck(requestParameters: CreateDeckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<YugiohDeckCreationResponse> {
        const response = await this.createDeckRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteIdRaw(requestParameters: DeleteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/deck`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteId(requestParameters: DeleteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteIdRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getDeckByIdRaw(requestParameters: GetDeckByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeckDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeckById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/deck`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeckDTOFromJSON(jsonValue));
    }

    /**
     */
    async getDeckById(requestParameters: GetDeckByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeckDTO> {
        const response = await this.getDeckByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDecksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeckDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/deck/get-all`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeckDTOFromJSON));
    }

    /**
     */
    async getDecks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeckDTO>> {
        const response = await this.getDecksRaw(initOverrides);
        return await response.value();
    }

}
