/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeckDTO,
  PDFCreationRequest,
  YugiohDeckCreationRequest,
  YugiohDeckCreationResponse,
} from '../models/index';
import {
    DeckDTOFromJSON,
    DeckDTOToJSON,
    PDFCreationRequestFromJSON,
    PDFCreationRequestToJSON,
    YugiohDeckCreationRequestFromJSON,
    YugiohDeckCreationRequestToJSON,
    YugiohDeckCreationResponseFromJSON,
    YugiohDeckCreationResponseToJSON,
} from '../models/index';

export interface CreateDeckRequest {
    yugiohDeckCreationRequest: YugiohDeckCreationRequest;
}

export interface CreatePDFRequest {
    request: PDFCreationRequest;
}

export interface DeleteIdRequest {
    id: string;
}

export interface GetDeckByIdRequest {
    id: string;
}

export interface GetImageRequest {
    cardId: number;
}

/**
 * 
 */
export class YugiohControllerApi extends runtime.BaseAPI {

    /**
     */
    async createDeckRaw(requestParameters: CreateDeckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<YugiohDeckCreationResponse>> {
        if (requestParameters['yugiohDeckCreationRequest'] == null) {
            throw new runtime.RequiredError(
                'yugiohDeckCreationRequest',
                'Required parameter "yugiohDeckCreationRequest" was null or undefined when calling createDeck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/create-deck`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: YugiohDeckCreationRequestToJSON(requestParameters['yugiohDeckCreationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => YugiohDeckCreationResponseFromJSON(jsonValue));
    }

    /**
     */
    async createDeck(requestParameters: CreateDeckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<YugiohDeckCreationResponse> {
        const response = await this.createDeckRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createPDFRaw(requestParameters: CreatePDFRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling createPDF().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['request'] != null) {
            queryParameters['request'] = requestParameters['request'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/create-pdf`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createPDF(requestParameters: CreatePDFRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createPDFRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteIdRaw(requestParameters: DeleteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/delete-deck`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteId(requestParameters: DeleteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteIdRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getDeckByIdRaw(requestParameters: GetDeckByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeckDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeckById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/get-deck`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeckDTOFromJSON(jsonValue));
    }

    /**
     */
    async getDeckById(requestParameters: GetDeckByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeckDTO> {
        const response = await this.getDeckByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDecksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeckDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/get-decks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeckDTOFromJSON));
    }

    /**
     */
    async getDecks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeckDTO>> {
        const response = await this.getDecksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getImageRaw(requestParameters: GetImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['cardId'] == null) {
            throw new runtime.RequiredError(
                'cardId',
                'Required parameter "cardId" was null or undefined when calling getImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/image/small/{cardId}`;
        urlPath = urlPath.replace(`{${"cardId"}}`, encodeURIComponent(String(requestParameters['cardId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getImage(requestParameters: GetImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
