/* tslint:disable */
/* eslint-disable */
/**
 * Short Url API
 * Short Url API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UrlDTO
 */
export interface UrlDTO {
    /**
     * 
     * @type {string}
     * @memberof UrlDTO
     */
    shortUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UrlDTO
     */
    targetUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UrlDTO
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof UrlDTO
     */
    creationDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof UrlDTO
     */
    calls?: number;
}

/**
 * Check if a given object implements the UrlDTO interface.
 */
export function instanceOfUrlDTO(value: object): value is UrlDTO {
    return true;
}

export function UrlDTOFromJSON(json: any): UrlDTO {
    return UrlDTOFromJSONTyped(json, false);
}

export function UrlDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'shortUrl': json['shortUrl'] == null ? undefined : json['shortUrl'],
        'targetUrl': json['targetUrl'] == null ? undefined : json['targetUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
        'calls': json['calls'] == null ? undefined : json['calls'],
    };
}

export function UrlDTOToJSON(json: any): UrlDTO {
    return UrlDTOToJSONTyped(json, false);
}

export function UrlDTOToJSONTyped(value?: UrlDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shortUrl': value['shortUrl'],
        'targetUrl': value['targetUrl'],
        'description': value['description'],
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
        'calls': value['calls'],
    };
}

