/* tslint:disable */
/* eslint-disable */
/**
 * Short Url API
 * Short Url API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UrlRequest
 */
export interface UrlRequest {
    /**
     * 
     * @type {string}
     * @memberof UrlRequest
     */
    term?: string;
    /**
     * Page number starting with a 0
     * @type {number}
     * @memberof UrlRequest
     */
    page?: number;
    /**
     * Size of the page
     * @type {string}
     * @memberof UrlRequest
     */
    size?: UrlRequestSizeEnum;
}


/**
 * @export
 */
export const UrlRequestSizeEnum = {
    _10: 'SIZE_10',
    _25: 'SIZE_25',
    _50: 'SIZE_50'
} as const;
export type UrlRequestSizeEnum = typeof UrlRequestSizeEnum[keyof typeof UrlRequestSizeEnum];


/**
 * Check if a given object implements the UrlRequest interface.
 */
export function instanceOfUrlRequest(value: object): value is UrlRequest {
    return true;
}

export function UrlRequestFromJSON(json: any): UrlRequest {
    return UrlRequestFromJSONTyped(json, false);
}

export function UrlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'term': json['term'] == null ? undefined : json['term'],
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function UrlRequestToJSON(json: any): UrlRequest {
    return UrlRequestToJSONTyped(json, false);
}

export function UrlRequestToJSONTyped(value?: UrlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'term': value['term'],
        'page': value['page'],
        'size': value['size'],
    };
}

